'use client';
import {useCallback,useEffect,useState} from 'react';
import styles from './BrokerConnectionManager.module.css';
type Status={state:string;connected:boolean;profile?:unknown};
export default function BrokerConnectionManager(){const[status,setStatus]=useState<Status>({state:'INITIALIZING',connected:false});const[token,setToken]=useState('');const[message,setMessage]=useState('Restoring saved broker configuration…');const[busy,setBusy]=useState(false);
 const refresh=useCallback(async()=>{try{const r=await fetch('/api/upstox/bootstrap',{cache:'no-store'});const d=await r.json() as Status;setStatus(d);setMessage(d.connected?'Saved Upstox session restored automatically.':d.state==='REAUTH_REQUIRED'?'Saved session expired. Reconnect Upstox once to continue.':'Broker configuration is ready; connect Upstox to start the session.');}catch{setStatus({state:'ERROR',connected:false});setMessage('Broker connection manager is unavailable.');}},[]);
 useEffect(()=>{void refresh()},[refresh]);
 async function manual(){if(!token.trim()||busy)return;setBusy(true);setMessage('Validating token with Upstox…');try{const r=await fetch('/api/upstox/manual-token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error??'Token rejected');setToken('');setMessage('Token validated and stored securely for automatic startup.');await refresh();}catch(e){setMessage(e instanceof Error?e.message:'Unable to connect token.');}finally{setBusy(false)}}
 async function disconnect(){setBusy(true);await fetch('/api/upstox/manual-token',{method:'DELETE'}).catch(()=>{});setStatus({state:'DISCONNECTED',connected:false});setMessage('Upstox session removed.');setBusy(false)}
 return <main className={styles.root}><section className={styles.hero}><div><h1>BROKER CONNECTION MANAGER</h1><p>Configure once. MarketLab restores a still-valid Upstox session automatically on startup.</p></div><div className={styles.state}>● {status.state}</div></section><div className={styles.notice}>{message}</div><div className={styles.grid}><section className={styles.card}><h3>UPSTOX OAUTH</h3><p>Recommended connection method. API credentials remain server-side and the resulting session is persisted for automatic MarketLab startup.</p><div className={styles.actions}><a className={`${styles.button} ${styles.primary}`} href="/api/upstox/login">{status.connected?'REAUTHORIZE UPSTOX':'CONNECT UPSTOX'}</a><button className={styles.button} onClick={()=>void refresh()}>REFRESH STATUS</button></div></section><section className={styles.card}><h3>MANUAL ACCESS TOKEN</h3><p>Development fallback. Paste a token once; MarketLab validates it with Upstox and stores it server-side. Never commit tokens to Git.</p><textarea className={styles.token} value={token} onChange={e=>setToken(e.target.value)} placeholder="Paste Upstox access token"/><div className={styles.actions}><button className={`${styles.button} ${styles.primary}`} disabled={busy||!token.trim()} onClick={()=>void manual()}>{busy?'WORKING…':'VALIDATE & SAVE TOKEN'}</button></div></section><section className={styles.card}><h3>AUTOMATIC STARTUP</h3><div className={styles.list}><div className={styles.row}><span>Broker configuration</span><b>SERVER-SIDE</b></div><div className={styles.row}><span>Saved session</span><b>{status.connected?'RESTORED':'NOT ACTIVE'}</b></div><div className={styles.row}><span>Options/Futures runtime</span><b>{status.connected?'READY TO INITIALIZE':'WAITING'}</b></div><div className={styles.row}><span>ASURA / Sentinel</span><b>{status.connected?'READY':'OFFLINE SAFE MODE'}</b></div></div></section><section className={styles.card}><h3>SESSION CONTROL</h3><p>Upstox access tokens still expire according to Upstox policy. MarketLab automatically restores valid sessions, but it cannot extend an expired broker token.</p><div className={styles.actions}><button className={`${styles.button} ${styles.danger}`} disabled={busy} onClick={()=>void disconnect()}>DISCONNECT & FORGET SESSION</button></div></section></div></main>}
